import "~/styles/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Lilita_One } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/navbar/navbar";
import SignIn from "~/components/navbar/sign-in";
import Footer from "~/components/footer/footer";

const inter = Lilita_One({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${inter.className} `}>
        <TRPCReactProvider>
          <div className=" mx-auto my-2 flex min-h-screen max-w-screen-xl flex-col px-2 lg:px-6">
            <SignIn />
            <Navbar />
            <main className="flex-auto"> {children}</main>
            <Footer />
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
